# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-14 01:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('users', models.CharField(max_length=20)),
                ('recv_name', models.CharField(max_length=20)),
                ('recv_phone', models.IntegerField()),
                ('native', models.CharField(max_length=20)),
                ('provice', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=20)),
                ('desc', tinymce.models.HTMLField()),
                ('status', models.BooleanField(verbose_name=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.IntegerField(verbose_name='登陆账号')),
                ('userpass', models.IntegerField(max_length=50, verbose_name='登陆密码')),
                ('nickname', models.CharField(max_length=20, verbose_name='用户昵称')),
                ('age', models.IntegerField(verbose_name='用户年龄')),
                ('gender', models.CharField(default='男', max_length=3, verbose_name='用户性别')),
                ('header', models.ImageField(upload_to='static/images/14.jpg', verbose_name='用户头像')),
                ('phone', models.IntegerField(default=110, verbose_name='联系方式')),
                ('email', models.CharField(default='123', max_length=40, verbose_name='电子邮箱')),
                ('regist_time', models.TimeField(auto_now=True, verbose_name='注册时间')),
                ('last_login_time', models.DateField(auto_now=True, verbose_name='上次登录时间')),
                ('status', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='addressUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.Users'),
        ),
        migrations.AddField(
            model_name='address',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
