# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-14 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_auto_20190314_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='userpass',
            field=models.IntegerField(verbose_name='登陆密码'),
        ),
    ]
