# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-16 07:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='店铺名称')),
                ('cover', models.ImageField(upload_to='static/storp/storpimg.png')),
                ('intro', models.CharField(max_length=255)),
                ('opener_time', models.DateTimeField(auto_now_add=True, verbose_name='开店时间')),
                ('status', models.IntegerField(default=0, verbose_name='店铺状态')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.Users', verbose_name='店铺所属用户')),
            ],
        ),
    ]
