# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-14 09:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='cover',
            field=models.ImageField(upload_to='static/store/storpimg.png'),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='店铺名称'),
        ),
        migrations.AlterField(
            model_name='store',
            name='opener_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='开店时间'),
        ),
        migrations.AlterField(
            model_name='store',
            name='status',
            field=models.IntegerField(default=0, verbose_name='店铺状态'),
        ),
        migrations.AlterField(
            model_name='store',
            name='users',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.Users', verbose_name='店铺所属用户'),
        ),
    ]
