# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-14 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Storp', '0002_auto_20190314_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='cover',
            field=models.ImageField(upload_to='static/storp/storpimg.png'),
        ),
    ]
