# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-16 07:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('prder_time', models.TimeField()),
                ('recv_name', models.CharField(max_length=10)),
                ('recv_address', models.TextField()),
                ('recv_phone', models.IntegerField()),
                ('recv_remark', models.CharField(max_length=255)),
                ('totale', models.IntegerField()),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Orderltem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('oi_goods_id', models.IntegerField()),
                ('oi_goods_name', models.CharField(max_length=20)),
                ('oi_goods_price', models.IntegerField()),
                ('oi_goods_count', models.IntegerField()),
                ('deal_price', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oreder.order')),
            ],
        ),
    ]
