# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-14 01:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Storp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('count', models.IntegerField()),
                ('add_time', models.TimeField()),
                ('desc', models.CharField(max_length=255)),
                ('goods_detail_type', models.CharField(max_length=255)),
                ('goods_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Storp.Store')),
            ],
        ),
        migrations.CreateModel(
            name='Goodsimage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('path', models.ImageField(upload_to='static/images')),
                ('status', models.ImageField(upload_to='static/imgages')),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GoodType.Goods')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gt_name', models.CharField(max_length=30)),
                ('cover', models.ImageField(upload_to='static/images')),
                ('gt_desc', models.TextField()),
            ],
        ),
    ]
