# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-16 07:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shopcart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('goods', models.CharField(max_length=20)),
                ('count', models.IntegerField()),
                ('add_time', models.TimeField()),
                ('subtotal', models.IntegerField()),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.Users')),
            ],
        ),
    ]
